import type { Metadata } from "next";
import { Geist, Roboto } from "next/font/google";
import "../globals.css";
import Header from "@/components/layout/header";
import FilterBar from "@/components/layout/filter-bar";
import { isAdmin } from "@/features/me/services/me-service";

const robotoSans = Roboto({
  variable: "--font-sans",
  subsets: ["latin"]
})

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const admin = await isAdmin()
  return (
    <html
      lang="fr"
      className={`${robotoSans.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col bg-zinc-100">
        <Header isAdmin={admin}/>
        <div className="flex-1 flex overflow-hidden">
          <FilterBar/>
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}