spring.application.name=lyra-backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5437/lyra_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Migration manuelle uniquement
spring.liquibase.enabled=false


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/lyra

# fait apparaitre le message d'erreur dans la réponse HTTP
server.error.include-message=always