import type { Metadata } from "next";
import { Geist, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import FilterBar from "@/components/layout/filter-bar";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/providers";

const robotoSans = Roboto({
  variable: "--font-sans",
  subsets: ["latin"]
})

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${robotoSans.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col bg-zinc-100">
        <Providers>
          {children}
        </Providers>
        <Toaster/>
      </body>
    </html>
  );
}
